apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: webhooks
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: infrastructure-config
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./webhooks"
  prune: true
  wait: true
